#!/usr/bin/python3
import sys


def factor(n):
    for i in range(2, n + 1):
        if n % i == 0:
            return "{}={}*{}".format(n, int(n / i), i)


with open(sys.argv[1], 'r') as f:
    for i in f:
        print(factor(int(i)))
